# Blog settings
permalink: /blog/:title


# My variables
name: few blocks
description: Intersections of art and technology
google_verification: true
google_verify: m0ZKYI4v5nRwtxec4YvMkyt8CjYQH7VmPxBraxoKXa8


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "CNAME"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
